title: Amir Mojiry
description: >-
  Web developer and app creator sharing projects, product notes, and privacy details.
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag
markdown: kramdown
permalink: pretty
baseurl: "/amirmojiry" # Set to "" if the repo is renamed to amirmojiry.github.io
url: "https://amirmojiry.github.io"
author: Amir Mojiry
github_username: amirmojiry
show_downloads: false
header_pages:
  - apps/index.md
  - blog/index.md
