title: Amir Mojiri
description: >-
  Web developer and app creator sharing projects, product notes, and privacy details.
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme
markdown: kramdown
permalink: pretty
baseurl: "" amirmojiry
url: "" https://amirMojiry.github.io
author: Amir Mojiri
github_username: amirMojiri
show_downloads: false
header_pages:
  - apps/index.md
  - blog/index.md
